export const COUNTRIES = [
  { code: 'DZ', name: 'Algeria', prefix: '+213' },
  { code: 'AO', name: 'Angola', prefix: '+244' },
  { code: 'BJ', name: 'Benin', prefix: '+229' },
  { code: 'BW', name: 'Botswana', prefix: '+267' },
  { code: 'BF', name: 'Burkina Faso', prefix: '+226' },
  { code: 'BI', name: 'Burundi', prefix: '+257' },
  { code: 'CV', name: 'Cabo Verde (Cape Verde)', prefix: '+238' },
  { code: 'CM', name: 'Cameroon', prefix: '+237' },
  { code: 'CF', name: 'Central African Republic', prefix: '+236' },
  { code: 'TD', name: 'Chad', prefix: '+235' },
  { code: 'KM', name: 'Comoros', prefix: '+269' },
  { code: 'CD', name: 'Democratic Republic of the Congo', prefix: '+243' },
  { code: 'CG', name: 'Republic of the Congo', prefix: '+242' },
  { code: 'DJ', name: 'Djibouti', prefix: '+253' },
  { code: 'EG', name: 'Egypt', prefix: '+20' },
  { code: 'GQ', name: 'Equatorial Guinea', prefix: '+240' },
  { code: 'ER', name: 'Eritrea', prefix: '+291' },
  { code: 'SZ', name: 'Eswatini (formerly Swaziland)', prefix: '+268' },
  { code: 'ET', name: 'Ethiopia', prefix: '+251' },
  { code: 'GA', name: 'Gabon', prefix: '+241' },
  { code: 'GM', name: 'Gambia', prefix: '+220' },
  { code: 'GH', name: 'Ghana', prefix: '+233' },
  { code: 'GN', name: 'Guinea', prefix: '+224' },
  { code: 'GW', name: 'Guinea-Bissau', prefix: '+245' },
  { code: 'CI', name: 'Ivory Coast (Côte d\'Ivoire)', prefix: '+225' },
  { code: 'KE', name: 'Kenya', prefix: '+254' },
  { code: 'LS', name: 'Lesotho', prefix: '+266' },
  { code: 'LR', name: 'Liberia', prefix: '+231' },
  { code: 'LY', name: 'Libya', prefix: '+218' },
  { code: 'MG', name: 'Madagascar', prefix: '+261' },
  { code: 'MW', name: 'Malawi', prefix: '+265' },
  { code: 'ML', name: 'Mali', prefix: '+223' },
  { code: 'MR', name: 'Mauritania', prefix: '+222' },
  { code: 'MU', name: 'Mauritius', prefix: '+230' },
  { code: 'MA', name: 'Morocco', prefix: '+212' },
  { code: 'MZ', name: 'Mozambique', prefix: '+258' },
  { code: 'NA', name: 'Namibia', prefix: '+264' },
  { code: 'NE', name: 'Niger', prefix: '+227' },
  { code: 'NG', name: 'Nigeria', prefix: '+234' },
  { code: 'RW', name: 'Rwanda', prefix: '+250' },
  { code: 'ST', name: 'Sao Tome and Principe', prefix: '+239' },
  { code: 'SN', name: 'Senegal', prefix: '+221' },
  { code: 'SC', name: 'Seychelles', prefix: '+248' },
  { code: 'SL', name: 'Sierra Leone', prefix: '+232' },
  { code: 'SO', name: 'Somalia', prefix: '+252' },
  { code: 'ZA', name: 'South Africa', prefix: '+27' },
  { code: 'SS', name: 'South Sudan', prefix: '+211' },
  { code: 'SD', name: 'Sudan', prefix: '+249' },
  { code: 'TZ', name: 'Tanzania', prefix: '+255' },
  { code: 'TG', name: 'Togo', prefix: '+228' },
  { code: 'TN', name: 'Tunisia', prefix: '+216' },
  { code: 'UG', name: 'Uganda', prefix: '+256' },
  { code: 'ZM', name: 'Zambia', prefix: '+260' },
  { code: 'ZW', name: 'Zimbabwe', prefix: '+263' },
]

export const ACCOUNT_TYPES = [
  {
    value: "market",
    label: "Market",
    description: "Shop GECO merchandise",
    icon: "cart",
  },
  {
    value: "developer",
    label: "Developer",
    description: "Game development tools & resources",
    icon: "code",
  },
  {
    value: "jampass",
    label: "JamPass",
    description: "Access live events & matches",
    icon: "ticket",
  },
  {
    value: "academy",
    label: "Academy",
    description: "Game development training",
    icon: "graduation",
  },
]

export const JAMPASS_SUB_TYPES = [
  { value: "outlet", label: "Outlet" },
  { value: "player", label: "Player" },
]

export const ACADEMY_SUB_TYPES = [
  { value: "admin", label: "Admin" },
  { value: "trainee", label: "Trainee" },
]